version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_DB=postgresdb
      - POSTGRES_USER=biighunter
      - POSTGRES_PASSWORD=1122
    ports:
      - "5432:5432"
    volumes:
      - server_ho-certbot:/etc/letsencrypt
      - pg_data:/var/lib/postgresql/data
    networks:
      Ho:

volumes:
  pg_slave_data:
  pg_data:
  mysql-data:
  server_ho-certbot:
    external: true
networks:
  Ho:
    external: true


  # web-server:    
  #   image: nginx:latest
  #   container_name: web_container
  #   environment:
  #     - POSTGRES_DB=postgresdb
  #     - POSTGRES_USER=biighunter
  #     - POSTGRES_PASSWORD=1122
  #     - POSTGRES_HOST="http://postgres:5432"
  #   expose:
  #     - 80
  #     - 443
  #   networks:
  #     - Ho


#---------------------
  # mysql:
  #   image: mysql:latest
  #   container_name: mysql
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=1122
  #     - MYSQL_DATABASE=mydb
  #     - MYSQL_USER=biighunter
  #     - MYSQL_PASSWORD=1122
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   networks:
  #     - Ho